# Generated by Django 5.2.7 on 2025-11-25 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('opportunity_type', models.CharField(choices=[('Job', 'Job'), ('Program', 'Program/Course'), ('Scholarship', 'Scholarship'), ('Admission', 'Admission')], max_length=20)),
                ('filters', models.JSONField(default=dict, help_text='e.g., required qualifications, minimum GPA')),
                ('tags', models.JSONField(default=list, help_text='List of keywords or tags for matching')),
                ('positive_tags', models.JSONField(blank=True, default=list, help_text='Tags that reward the match score')),
                ('negative_tags', models.JSONField(blank=True, default=list, help_text='Tags that penalize the match score')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='institutions.institution')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.UUIDField(db_column='match_record_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_stale', models.BooleanField(default=False)),
                ('match_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('winning_argument', models.TextField()),
                ('losing_argument', models.TextField()),
                ('matched_tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_records', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_records', to='opportunities.opportunity')),
            ],
            options={
                'unique_together': {('applicant', 'opportunity')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Submitted', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'unique_together': {('applicant', 'opportunity')},
            },
        ),
    ]
