# Generated by Django 6.0 on 2026-01-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='negative_tags',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='positive_tags',
        ),
    ]
