# Generated by Django 5.2.7 on 2025-11-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
