# Generated by Django 6.0 on 2026-01-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file'),
        ('opportunities', '0002_remove_opportunity_filters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='document_categories',
            field=models.ManyToManyField(blank=True, help_text='Document categories required for this opportunity', related_name='opportunities', to='documents.documentcategory'),
        ),
    ]
