# Generated by Django 5.2.8 on 2025-11-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0002_opportunity_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="negative_tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Tags that penalize the match score"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="positive_tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Tags that reward the match score"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
