# Generated by Django 6.0.1 on 2026-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0003_opportunity_document_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="letter",
            field=models.TextField(
                blank=True,
                help_text="A motivational letter or additional info from the applicant.",
                null=True,
            ),
        ),
    ]
