# Generated by Django 6.0 on 2026-02-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_application_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('In Review', 'In Review'), ('Pending Verification', 'Pending Verification'), ('Waitlisted', 'Waitlisted')], default='Submitted', max_length=100),
        ),
    ]
