# Generated by Django 6.0.2 on 2026-02-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0005_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="submitted_documents",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map of requirement ID to Document ID for specific requirements",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="specific_requirements",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of specific document requirements (e.g., [{'id': '1', 'label': 'AWS Cert', 'mandatory': True}])",
            ),
        ),
    ]
