# Generated by Django 5.2.8 on 2025-11-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(
                blank=True, default=list, help_text="List of user interests or tags"
            ),
        ),
    ]
