# Generated by Django 5.2.7 on 2025-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
