# Generated by Django 6.0 on 2026-02-19 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_institution_description_institution_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('label', models.CharField(help_text='A friendly name for this key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='institutions.institution')),
            ],
        ),
    ]
