# Generated by Django 5.2.8 on 2025-11-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="storage_path",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, max_length=1024, null=True, upload_to="documents/"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash of the file to ensure integrity",
                max_length=255,
            ),
        ),
    ]
