# Generated by Django 5.2.7 on 2025-11-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_storage_path_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, help_text='Content or description of the document'),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the document', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, help_text='Type of the document', max_length=100),
        ),
    ]
