# Generated by Django 5.2.7 on 2025-11-25 04:10

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_content_document_title_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=documents.models.generate_unique_filename),
        ),
    ]
